# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utm_source',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
