# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column=b'Name', db_index=True, max_length=255)),
                ('hostname', models.CharField(db_column=b'Hostname__c', db_index=True, max_length=255)),
                ('instance_id', models.CharField(db_column=b'Instance_ID__c', db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column=b'Name', db_index=True, max_length=255)),
                ('title', models.CharField(db_column=b'Title', max_length=255)),
                ('address', models.CharField(db_column=b'Address', max_length=255)),
                ('annual_revenue', models.BigIntegerField(db_column=b'AnnualRevenue')),
            ],
        ),
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column=b'Name', db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, db_column=b'Comment__c', null=True)),
                ('config_file_download', models.TextField(blank=True, db_column=b'Config_File_Download__c', null=True)),
                ('current_city', models.CharField(blank=True, db_column=b'Current_City__c', max_length=255, null=True)),
                ('current_ip_address', models.CharField(blank=True, db_column=b'Current_IP_Address__c', max_length=255, null=True)),
                ('current_isp', models.CharField(blank=True, db_column=b'Current_ISP__c', max_length=255, null=True)),
                ('current_state_region', models.CharField(blank=True, db_column=b'Current_State_Region__c', max_length=255, null=True)),
                ('date_shipped', models.DateField(blank=True, db_column=b'Date_Shipped__c', null=True)),
                ('delivered_internal', models.BooleanField(db_column=b'Delivered__c', default=False)),
                ('delivered_status', models.TextField(blank=True, db_column=b'Delivery_Status__c', null=True)),
                ('ec2_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.EC2Instance')),
            ],
        ),
    ]
