# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0002_ec2instance_lead_raspberrypi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ec2instance',
            options={'verbose_name': 'EC2 Instance', 'verbose_name_plural': 'EC2 Instances'},
        ),
        migrations.AlterModelOptions(
            name='raspberrypi',
            options={'verbose_name': 'Raspberry PI', 'verbose_name_plural': 'Raspberry PIs'},
        ),
    ]
