# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0002_user_utm_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
