# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='raspberry_pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.RaspberryPi'),
        ),
    ]
