# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0003_auto_20171102_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_account',
            field=models.BooleanField(db_column=b'Facebook_Account__c', default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook_account_status',
            field=models.CharField(blank=True, db_column=b'Facebook_Account_Status__c', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook_email',
            field=models.CharField(blank=True, db_column=b'FB_email__c', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook_friends',
            field=models.IntegerField(blank=True, db_column=b'FB_friends__c', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook_secret',
            field=models.CharField(blank=True, db_column=b'FB_secret__c', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='google_account',
            field=models.BooleanField(db_column=b'Google_Account__c', default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='google_account_status',
            field=models.CharField(blank=True, db_column=b'Google_Account_Status__c', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, db_column=b'MobilePhone', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, db_column=b'Phone', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='raspberry_pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.RaspberryPi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, db_column=b'Address', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='annual_revenue',
            field=models.BigIntegerField(blank=True, db_column=b'AnnualRevenue', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, db_column=b'Title', max_length=255, null=True),
        ),
    ]
