# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 01:12
from __future__ import unicode_literals

from django.db import migrations


def update_leads(apps, schema_editor):
    Lead = apps.get_model('adsrental', 'Lead')
    RaspberryPi = apps.get_model('adsrental', 'RaspberryPi')
    for lead in Lead.objects.all():
        raspberry_pi = RaspberryPi.objects.filter(leadid=lead.leadid).first()
        if not raspberry_pi:
            continue
        lead.raspberry_pi = raspberry_pi
        lead.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0003_lead_raspberry_pi'),
    ]

    operations = [
        migrations.RunPython(update_leads),
    ]
