# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0004_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='facebook_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='google_account',
            field=models.BooleanField(default=False),
        ),
    ]
