# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0004_auto_20171103_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspberrypi',
            old_name='delivered_status',
            new_name='delivery_status',
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='sf_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='facebook_friends',
            field=models.IntegerField(blank=True, db_column=b'FB_friends__c', null=True),
        ),
    ]
