# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0005_auto_20171103_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='owner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='sf_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
