# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0005_auto_20171205_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
