# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-06 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0006_auto_20171205_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_account_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Banned', 'Banned')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='google_account_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Banned', 'Banned')], max_length=255, null=True),
        ),
    ]
