# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0007_ec2instance_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ec2instance',
            old_name='sf_id',
            new_name='salesforce_id',
        ),
        migrations.RenameField(
            model_name='raspberrypi',
            old_name='sf_id',
            new_name='salesforce_id',
        ),
    ]
