# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-06 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0008_auto_20171206_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
