# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0008_auto_20171103_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
