# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0009_auto_20171206_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
