# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0010_auto_20171104_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
