# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0010_auto_20171206_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
