# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0012_auto_20171104_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
