# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0013_auto_20171104_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_sent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('system_mod_stamp', models.DateTimeField(blank=True, null=True)),
                ('last_referenced_date', models.DateTimeField(blank=True, null=True)),
                ('fb_updated_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_reveived_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_account_status_last_checked', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_friends', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_changed', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('log_file_link', models.TextField(blank=True, max_length=1024, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('fb_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('last_viewed_date', models.DateTimeField(blank=True, null=True)),
                ('ad_account_status', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_account_active', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('login_notifications_disabled', models.BooleanField(default=False)),
                ('created_by_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_email', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Browser Extension',
                'verbose_name_plural': 'Browser Extensions',
            },
        ),
    ]
