# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0014_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pi_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
