# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-14 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0015_lead_pi_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='raspberry_pi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.RaspberryPi'),
        ),
    ]
