# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0015_auto_20171104_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='activation_isp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
