# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0016_auto_20171104_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
