# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-28 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0018_lead_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fb_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fb_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
