# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-28 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0019_auto_20171228_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_sync_adsdb',
            field=models.BooleanField(default=False),
        ),
    ]
