# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-11 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0020_lead_is_sync_adsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='photo_id',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
