# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0021_lead_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='last_offline_reported',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
