# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0022_raspberrypi_last_offline_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='last_offline_reported',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
