# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0024_customerioevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='leadid',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
