# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0025_auto_20180115_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerioevent',
            name='lead',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.Lead'),
        ),
    ]
