# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-19 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0026_customerioevent_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='raspberry_pi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.RaspberryPi', unique=True),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='rpid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
