# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-19 06:35
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


def populate_first_tested(apps, schema_editor):
    RaspberryPi = apps.get_model('adsrental', 'RaspberryPi')
    for raspberry_pi in RaspberryPi.objects.filter(first_seen__isnull=False):
        raspberry_pi.first_tested = raspberry_pi.first_seen - datetime.timedelta(hours=1)
        raspberry_pi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0028_auto_20180119_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='first_tested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_first_tested, reverse_code=migrations.RunPython.noop),
    ]
