# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0028_auto_20180119_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='first_tested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
