# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-21 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0029_raspberrypi_first_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='restart_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='update_required',
            field=models.BooleanField(default=False),
        ),
    ]
