# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-21 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0030_auto_20180121_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberrypi',
            name='update_required',
        ),
    ]
