# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0032_raspberrypi_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rpid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('terminated', 'Terminated'), ('pending', 'Pending'), ('stopping', 'Stopping'), ('missing', 'Missing')], db_index=True, default='missing', max_length=255)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('password', models.CharField(default=b'Dk.YDq8pXQS-R5ZAn84Lgma9rFvGlfvL', max_length=255)),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.Lead')),
            ],
        ),
    ]
