# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0033_ec2instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.Lead'),
        ),
    ]
