# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0034_auto_20180123_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='ssh_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='tunnel_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='web_up',
            field=models.BooleanField(default=False),
        ),
    ]
