# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0035_auto_20180123_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ec2instance',
            options={'verbose_name': 'EC2 Instance', 'verbose_name_plural': 'EC2 Instances'},
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='last_troubleshoot',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
