# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0036_auto_20180123_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.Lead'),
        ),
    ]
