# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0037_auto_20180123_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='raspberry_pi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.RaspberryPi'),
        ),
    ]
