# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0039_auto_20180124_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='splashtop_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
