# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0040_lead_splashtop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('terminated', 'Terminated'), ('pending', 'Pending'), ('stopping', 'Stopping'), ('missing', 'Missing'), ('shutting-down', 'Shutting down')], db_index=True, default='missing', max_length=255),
        ),
    ]
