# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0041_auto_20180125_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec2instance',
            name='raspberry_pi',
        ),
    ]
