# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0044_leadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='version',
            field=models.CharField(default='2.4.6', max_length=255),
        ),
    ]
