# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0046_lead_old_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerioevent',
            name='name',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('offline', 'Offline'), ('lead_approved', 'Approved'), ('banned', 'Banned')], max_length=255),
        ),
    ]
