# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0050_lead_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='sf_leadid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
