# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-03 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0051_auto_20180202_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
