# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0053_auto_20180203_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookProxyLead',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('adsrental.lead',),
        ),
        migrations.AddField(
            model_name='lead',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(choices=[('[Empty]', '[Empty]'), ('ACM', 'ACM'), ('FBM', 'FBM')], default='[Empty]', max_length=20),
        ),
    ]
