# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0054_auto_20180204_0508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookProxyLead',
        ),
        migrations.CreateModel(
            name='ReportProxyLead',
            fields=[
            ],
            options={
                'verbose_name': 'Report Lead',
                'proxy': True,
                'verbose_name_plural': 'Report Leads',
            },
            bases=('adsrental.lead',),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_touch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='touch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(choices=[('ACM', 'ACM'), ('FBM', 'FBM'), ('[Empty]', '[Empty]')], default='[Empty]', max_length=20),
        ),
    ]
