# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0056_bundler'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bundler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.Bundler'),
        ),
    ]
