# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0057_lead_bundler'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bundler',
            name='bank_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bundler',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bundler',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bundler',
            name='skype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bundler',
            name='adsdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
