# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0058_auto_20180205_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundler',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
