# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0061_leadhistorymonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadhistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
