# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0062_auto_20180206_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='old_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified')], default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified')], default='Available', max_length=40),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='version',
            field=models.CharField(default='1.0.10', max_length=20),
        ),
    ]
