# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 22:51
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


def populate_wrong_password_date(apps, schema_editor):
    Lead = apps.get_model('adsrental', 'Lead')
    for lead in Lead.objects.all():
        lead.wrong_password_date = timezone.now() if lead.wrong_password else None
        lead.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0063_auto_20180207_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='wrong_password_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_wrong_password_date, reverse_code=migrations.RunPython.noop),
    ]
