# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0064_lead_wrong_password_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='google_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='google_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
