# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0065_auto_20180208_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('old_value', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsrental.Lead')),
            ],
        ),
    ]
