# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0066_leadchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPiSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stated_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='leadhistory',
            options={'verbose_name': 'Lead History', 'verbose_name_plural': 'Lead Histories'},
        ),
        migrations.AlterModelOptions(
            name='leadhistorymonth',
            options={'verbose_name': 'Lead History Month', 'verbose_name_plural': 'Lead Histories Month'},
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='online_since_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raspberrypisession',
            name='raspberry_pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsrental.RaspberryPi'),
        ),
    ]
