# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0067_auto_20180208_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspberrypisession',
            old_name='stated_date',
            new_name='start_date',
        ),
    ]
