# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 21:30
from __future__ import unicode_literals

from django.db import migrations, models


def populate_shipstation_order_number(apps, schema_editor):
    Lead = apps.get_model('adsrental', 'Lead')
    for lead in Lead.objects.all():
        lead.shipstation_order_number = lead.account_name
        lead.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0068_auto_20180208_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='shipstation_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(populate_shipstation_order_number, reverse_code=migrations.RunPython.noop),
    ]
