# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0069_lead_shipstation_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(choices=[('ACM', 'ACM'), ('FBM', 'FBM'), ('ADB', 'ADB'), ('[Empty]', '[Empty]')], default='[Empty]', max_length=20),
        ),
    ]
