# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0070_auto_20180209_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec2instance',
            name='web_up',
        ),
    ]
