# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0072_ec2instance_tunnel_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadchange',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
