# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0073_leadchange_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sf_leadid',
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='version',
            field=models.CharField(default='1.0.20', max_length=20),
        ),
    ]
