# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0074_auto_20180215_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
