# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0079_lead_disqualify_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
