# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0080_lead_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fb_friends',
            field=models.BigIntegerField(default=0),
        ),
    ]
