# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0081_auto_20180301_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerioevent',
            name='sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='customerio_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
