# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0082_auto_20180301_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ship_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
