# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0083_lead_ship_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='qualified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='email',
            field=models.CharField(blank=True, db_index=True, help_text='Lead email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='hostname',
            field=models.CharField(blank=True, help_text='Public EC2 hostname. Updates everytime EC2 restarts. RPi use it to create tunnels.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='instance_id',
            field=models.CharField(blank=True, db_index=True, help_text='AWS EC2 ID.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Public EC2 IP. Updates everytime EC2 restarts.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Obsolete field'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time when instance state was synced back from AWS'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='last_troubleshoot',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time RaspberryPi tested tunnels. Should be updated every 10 minutes if device is online and up-to-date.'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='lead',
            field=models.OneToOneField(blank=True, help_text='Corresponding lead', null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.Lead'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='password',
            field=models.CharField(default='AdsInc18', help_text='Password for RDP session', max_length=255),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='rpid',
            field=models.CharField(blank=True, db_index=True, help_text='RPID that was inserted to EC2 metadata', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='ssh_up',
            field=models.BooleanField(default=False, help_text='Obsolete field'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('terminated', 'Terminated'), ('pending', 'Pending'), ('stopping', 'Stopping'), ('missing', 'Missing'), ('shutting-down', 'Shutting down')], db_index=True, default='missing', help_text='Status of EC2, same as in AWS UI', max_length=255),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='tunnel_up',
            field=models.BooleanField(default=False, help_text='Obsolete field'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='tunnel_up_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time both tunnel and reverse tunnels were online. Chcecked every 10 minutes.'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='version',
            field=models.CharField(default='2.4.6', help_text='AWS EC2 Firmware version', max_length=255),
        ),
    ]
