# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0085_lead_adsdb_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='version',
            field=models.CharField(default='2.8', help_text='AWS EC2 Firmware version', max_length=255),
        ),
    ]
