# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0086_auto_20180309_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='last_troubleshoot',
            field=models.DateTimeField(blank=True, help_text='Last time RaspberryPi tested tunnels. Should be updated every 10 minutes if device is online and up-to-date.', null=True),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='tunnel_up_date',
            field=models.DateTimeField(blank=True, help_text='Last time both tunnel and reverse tunnels were online. Chcecked every 10 minutes.', null=True),
        ),
    ]
