# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0087_auto_20180309_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberrypi',
            name='ec2_hostname',
        ),
        migrations.RemoveField(
            model_name='raspberrypi',
            name='ipaddress',
        ),
    ]
