# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0089_auto_20180309_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundler',
            name='adsdb_id',
            field=models.IntegerField(blank=True, help_text='ID from adsdb database', null=True),
        ),
        migrations.AlterField(
            model_name='customerioevent',
            name='kwargs',
            field=models.TextField(blank=True, help_text='Extra data sent to event, like hours_offline', null=True),
        ),
        migrations.AlterField(
            model_name='customerioevent',
            name='lead',
            field=models.ForeignKey(blank=True, default=None, help_text='Linked lead.', null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.Lead'),
        ),
        migrations.AlterField(
            model_name='customerioevent',
            name='name',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('offline', 'Offline'), ('lead_approved', 'Approved'), ('banned', 'Banned')], help_text='Event name. Used in customer.io filters.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerioevent',
            name='sent',
            field=models.BooleanField(default=True, help_text='Is published to customer.io or not.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='account_name',
            field=models.CharField(blank=True, help_text='Obsolete, was used in SF, should be removed', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='adsdb_account_id',
            field=models.CharField(blank=True, help_text='Corresponding Account ID in Adsdb database. used for syncing between databases.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ban_reason',
            field=models.CharField(blank=True, choices=[('Google - Policy', 'Google - Policy'), ('Google - Billing', 'Google - Billing'), ('Google - Unresponsive User', 'Google - Unresponsive User'), ('Facebook - Policy', 'Facebook - Policy'), ('Facebook - Suspicious', 'Facebook - Suspicious'), ('Facebook - Lockout', 'Facebook - Lockout'), ('Facebook - Unresponsive User', 'Facebook - Unresponsive User'), ('Duplicate', 'Duplicate'), ('Bad ad account', 'Bad ad account'), ('Other', 'Other')], help_text='Populated from ban form', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='billed',
            field=models.BooleanField(default=False, help_text='Does lead received his payment.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='bundler',
            field=models.ForeignKey(blank=True, default=None, help_text='New UTM source representation', null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.Bundler'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='bundler_paid',
            field=models.BooleanField(default=False, help_text='Is revenue paid to bundler.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='customerio_enabled',
            field=models.BooleanField(default=True, help_text='If False, customer.io event will not be sent for this lead. However, they are created.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='disqualify_reason',
            field=models.CharField(blank=True, choices=[("Doesn't meet friend requirements", "Doesn't meet friend requirements"), ("Doesn't meet age requirements", "Doesn't meet age requirements"), ('Fake FB', 'Fake FB'), ('Fake Google', 'Fake Google'), ('Non US account', 'Non US account'), ('Other', 'Other')], help_text='Not used', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, help_text='Should be unique', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='facebook_account',
            field=models.BooleanField(default=False, help_text='True if account is Facebook. facebook_account_status, fb_email, fb_secret should be also filled'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='google_account',
            field=models.BooleanField(default=False, help_text='True if account is google. google_account_status, google_email, google_password should be also filled'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_sync_adsdb',
            field=models.BooleanField(default=False, help_text='Obsolete field. Use adsdb_account_id instead.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_touch_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead was touched for the last time.', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='leadid',
            field=models.CharField(db_index=True, help_text='UUID is now used as a primary key for lead', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, help_text='Not shown when you hover user name in admin interface.', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='old_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified')], default=None, help_text='Used to restore previous status on Unban action', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, help_text='Formatted phone number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='photo_id',
            field=models.FileField(blank=True, help_text='Photo uploaded by user on registration.', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pi_delivered',
            field=models.BooleanField(default=False, help_text='Is RaspberryPi deliveered to end user.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='qualified_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead was marked as qualified for the last time.', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='raspberry_pi',
            field=models.OneToOneField(blank=True, default=None, help_text='Linked RaspberryPi device', null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.RaspberryPi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ship_date',
            field=models.DateField(blank=True, help_text='Date when order was shipped. Populated from shipstation sync.', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='shipstation_order_number',
            field=models.CharField(blank=True, help_text='Populated on mark as qualified, when SS ordeer is created.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='splashtop_id',
            field=models.CharField(blank=True, help_text='Splashtop ID reported by user.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified')], default='Available', help_text='All statuses except for Banned are considered as Active', max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tested',
            field=models.BooleanField(default=False, help_text='Obsolete field. Use first_tested instead.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='touch_count',
            field=models.IntegerField(default=0, help_text='Increased every time you do Touch action for this lead.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='usps_tracking_code',
            field=models.CharField(blank=True, help_text='Tracking code. Populated by sync_from-shipstation once order is shipped', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, help_text='Bundler UTM. Obsolete, use bundler instead', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='wrong_password',
            field=models.BooleanField(default=False, help_text='Is password wrong now. Should be merged with wrong_password_date'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='wrong_password_date',
            field=models.DateTimeField(blank=True, help_text='Date when password was reported as wrong.', null=True),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='days_offline',
            field=models.IntegerField(default=0, help_text='Days when device had been online less than 12 hours.'),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='days_online',
            field=models.IntegerField(default=0, help_text='Days when device had been online more than 12 hours.'),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='days_wrong_password',
            field=models.IntegerField(default=0, help_text='Days when wrong password was reported at least once.'),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='lead',
            field=models.ForeignKey(help_text='Linked lead.', on_delete=django.db.models.deletion.CASCADE, to='adsrental.Lead'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, default=b'', help_text=b'If not NULL, leads in dashboard will be filtered by this utm_source. SHould be changed to bundler.', max_length=255),
        ),
    ]
