# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0091_raspberrypi_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If inactive, landing/sugnup page will not be shown for this utm_source.'),
        ),
    ]
