# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0092_bundler_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadchange',
            name='old_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
