# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0093_auto_20180314_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerioevent',
            name='name',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('offline', 'Offline'), ('lead_approved', 'Approved'), ('banned', 'Banned'), ('available_banned', 'Banned from available status')], help_text='Event name. Used in customer.io filters.', max_length=255),
        ),
    ]
