# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0094_auto_20180315_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tracking_info',
            field=models.TextField(blank=True, help_text='Raw response from secure.shippingapis.com', null=True),
        ),
    ]
