# Generated by Django 2.0.3 on 2018-03-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0097_auto_20180326_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='ban_reason',
            field=models.CharField(blank=True, choices=[('Google - Policy', 'Google - Policy'), ('Google - Billing', 'Google - Billing'), ('Google - Unresponsive User', 'Google - Unresponsive User'), ('Facebook - Policy', 'Facebook - Policy'), ('Facebook - Suspicious', 'Facebook - Suspicious'), ('Facebook - Lockout', 'Facebook - Lockout'), ('Facebook - Unresponsive User', 'Facebook - Unresponsive User'), ('Duplicate', 'Duplicate'), ('Bad ad account', 'Bad ad account'), ('Other', 'Other')], help_text='Populated from ban form', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadaccount',
            name='old_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified')], default=None, help_text='Used to restore previous status on Unban action', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadaccount',
            name='qualified_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead was marked as qualified for the last time.', null=True),
        ),
        migrations.AlterField(
            model_name='leadaccount',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified')], max_length=50),
        ),
    ]
