# Generated by Django 2.0.3 on 2018-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0098_auto_20180326_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccount',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified')], default='Available', max_length=50),
        ),
    ]
