# Generated by Django 2.0.3 on 2018-03-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0099_auto_20180326_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccount',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_accounts', related_query_name='lead_account', to='adsrental.Lead'),
        ),
    ]
