# Generated by Django 2.0.3 on 2018-03-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0100_auto_20180326_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='adsdb_account_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ban_reason',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='bundler_paid',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='disqualify_reason',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='facebook_account_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fb_email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fb_friends',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fb_profile_url',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fb_secret',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='google_account',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='google_account_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='google_email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='google_password',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_sync_adsdb',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='qualified_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='wrong_password',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='wrong_password_date',
        ),
    ]
