# Generated by Django 2.0.3 on 2018-03-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0101_auto_20180328_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistorymonth',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum to be paid to lead', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leadhistorymonth',
            name='max_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max payment to lead, depends on qualified date and his accounts.', max_digits=6, null=True),
        ),
    ]
