# Generated by Django 2.0.3 on 2018-03-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0102_auto_20180329_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='billed',
            field=models.BooleanField(default=False, help_text='Did lead receive his payment.'),
        ),
        migrations.AddField(
            model_name='leadaccount',
            name='last_touch_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead account was touched for the last time.', null=True),
        ),
        migrations.AddField(
            model_name='leadaccount',
            name='touch_count',
            field=models.IntegerField(default=0, help_text='Increased every time you do Touch action for this lead account.'),
        ),
    ]
