# Generated by Django 2.0.3 on 2018-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0103_auto_20180329_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='note',
            field=models.TextField(blank=True, help_text='Not shown when you hover user name in admin interface.', null=True),
        ),
    ]
