# Generated by Django 2.0.3 on 2018-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0105_auto_20180330_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistorymonth',
            name='paid',
            field=models.BooleanField(default=False, help_text='Is sum paid to lead'),
        ),
    ]
