# Generated by Django 2.0.3 on 2018-04-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0106_leadhistorymonth_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bundler',
            field=models.ForeignKey(blank=True, help_text='If not NULL, leads in dashboard will be filtered by this bundler.utm_source.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adsrental.Bundler'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, default='', help_text='Obsolete', max_length=255),
        ),
    ]
