# Generated by Django 2.0.3 on 2018-04-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0107_auto_20180402_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadhistorymonth',
            name='paid',
        ),
        migrations.AddField(
            model_name='leadhistorymonth',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=False, help_text='Sum paid tot lead', max_digits=6),
        ),
    ]
