# Generated by Django 2.0.3 on 2018-04-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0108_auto_20180402_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum paid tot lead', max_digits=6, null=True),
        ),
    ]
