# Generated by Django 2.0.3 on 2018-04-02 21:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0109_auto_20180402_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum to be paid to lead', max_digits=6),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum paid tot lead', max_digits=6),
        ),
    ]
