# Generated by Django 2.0.3 on 2018-04-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0110_auto_20180402_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadOnlyLead',
            fields=[
            ],
            options={
                'verbose_name': 'Read-only Lead',
                'verbose_name_plural': 'Read-only Leads',
                'proxy': True,
                'indexes': [],
            },
            bases=('adsrental.lead',),
        ),
    ]
