# Generated by Django 2.0.3 on 2018-04-05 13:18

from django.db import migrations


def add_permissions(apps, schema_editor):
    pass


def remove_permissions(apps, schema_editor):
    """Reverse the above additions of permissions."""
    Permission = apps.get_model('auth.Permission')

    # This cascades to Group
    for p in Permission.objects.all():
        if p.content_type.app_label == 'salesforce_handler':
            p.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0113_readonlyleadaccount'),
    ]

    operations = [
        migrations.RunPython(remove_permissions, add_permissions),
    ]
