# Generated by Django 2.0.3 on 2018-04-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0114_auto_20180405_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': (('view', 'Can access lead info'),)},
        ),
        migrations.AlterModelOptions(
            name='leadaccount',
            options={'permissions': (('view', 'Can access lead account info'),)},
        ),
    ]
