# Generated by Django 2.0.3 on 2018-04-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0115_auto_20180405_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerioevent',
            name='name',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('offline', 'Offline'), ('lead_approved', 'Approved'), ('banned', 'Banned'), ('available_banned', 'Banned from available status'), ('security_checkpoint', 'Security checkpoint reported')], help_text='Event name. Used in customer.io filters.', max_length=255),
        ),
    ]
