# Generated by Django 2.0.3 on 2018-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0116_auto_20180406_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccount',
            name='ban_reason',
            field=models.CharField(blank=True, choices=[('Google - Policy', 'Google - Policy'), ('Google - Billing', 'Google - Billing'), ('Google - Unresponsive User', 'Google - Unresponsive User'), ('Facebook - Policy', 'Facebook - Policy'), ('Facebook - Suspicious', 'Facebook - Suspicious'), ('Facebook - Lockout', 'Facebook - Lockout'), ('Facebook - Unresponsive User', 'Facebook - Unresponsive User'), ('Duplicate', 'Duplicate'), ('Bad ad account', 'Bad ad account'), ('auto_offline', 'Auto: offline for 2 weeks'), ('auto_wrong_password', 'Auto: wrong password for 2 weeks'), ('auto_checkpoint', 'Auto: reported security checkpoint for 2 weeks'), ('Other', 'Other')], help_text='Populated from ban form', max_length=50, null=True),
        ),
    ]
