# Generated by Django 2.0.3 on 2018-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0118_leadaccount_last_security_checkpoint_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='bundler_paid_date',
            field=models.DateTimeField(blank=True, help_text='Date when bundler got his payment for this lead for the last time.', null=True),
        ),
    ]
