# Generated by Django 2.0.3 on 2018-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0119_leadaccount_bundler_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='enable_chargeback',
            field=models.BooleanField(default=True, help_text='If inactive, no chargeback will be calculated for lead accounts.'),
        ),
    ]
