# Generated by Django 2.0.3 on 2018-04-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0120_bundler_enable_chargeback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='billed',
            field=models.BooleanField(default=False, help_text='Account billed to Ads Inc.'),
        ),
    ]
