# Generated by Django 2.0.3 on 2018-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0121_auto_20180417_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, help_text='When RaspberryPi delivered to end user.', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pi_delivered',
            field=models.BooleanField(default=False, help_text='Is RaspberryPi delivered to end user.'),
        ),
    ]
