# Generated by Django 2.0.3 on 2018-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0123_bundlerpaymentsreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlerpaymentsreport',
            name='pdf',
            field=models.FileField(upload_to='bundler_payments_reports'),
        ),
    ]
