# Generated by Django 2.0.3 on 2018-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0124_auto_20180420_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlerpaymentsreport',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
