# Generated by Django 2.0.3 on 2018-04-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0125_auto_20180420_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='pay_check',
            field=models.BooleanField(default=True, help_text='User does not appear in check reports if turned off.'),
        ),
    ]
