# Generated by Django 2.0.3 on 2018-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0126_leadaccount_pay_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='antidetect_last_touch_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead account was antidetect touched for the last time.', null=True),
        ),
        migrations.AddField(
            model_name='leadaccount',
            name='antidetect_touch_count',
            field=models.IntegerField(default=0, help_text='Increased every time you do Antidetect Touch action for this lead account.'),
        ),
    ]
