# Generated by Django 2.0.3 on 2018-04-26 02:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0129_leadaccount_sync_with_adsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='facebook_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('125'), help_text='Payout for facebook accounts', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='google_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('125'), help_text='Payout for google accounts', max_digits=8),
        ),
    ]
