# Generated by Django 2.0.3 on 2018-04-26 22:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0130_auto_20180425_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='pay_split',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to bundler admin.', max_digits=8),
        ),
    ]
