# Generated by Django 2.0.3 on 2018-04-26 23:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0131_bundler_pay_split'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundler',
            old_name='pay_split',
            new_name='facebook_pay_split',
        ),
        migrations.AddField(
            model_name='bundler',
            name='google_pay_split',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to bundler admin.', max_digits=8),
        ),
    ]
