# Generated by Django 2.0.3 on 2018-04-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0132_auto_20180426_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlerpaymentsreport',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
