# Generated by Django 2.0.3 on 2018-04-30 13:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0134_auto_20180430_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundler',
            name='facebook_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to parent bundler.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='bundler',
            name='google_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to parent bundler.', max_digits=8),
        ),
    ]
