# Generated by Django 2.0.3 on 2018-05-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0135_auto_20180430_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccount',
            name='bundler_paid_date',
            field=models.DateField(blank=True, help_text='Date when bundler got his payment for this lead for the last time.', null=True),
        ),
    ]
