# Generated by Django 2.0.3 on 2018-05-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0137_auto_20180503_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlerpaymentsreport',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
