# Generated by Django 2.0.3 on 2018-05-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0138_bundlerpaymentsreport_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlerpaymentsreport',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
