# Generated by Django 2.0.3 on 2018-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0140_ec2instance_last_rdp_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='instance_type',
            field=models.CharField(default='t2.micro', help_text='Size of AWS EC2', max_length=50),
        ),
    ]
