# Generated by Django 2.0.3 on 2018-05-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0142_auto_20180518_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='instance_type',
            field=models.CharField(choices=[('t2.micro', 'Micro'), ('t2.medium', 'Medium'), ('t2.large', 'Large')], default='t2.medium', help_text='Size of AWS EC2', max_length=50),
        ),
    ]
