# Generated by Django 2.0.5 on 2018-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0146_auto_20180524_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='instance_type',
            field=models.CharField(choices=[('t2.micro', 'T2 Micro'), ('t2.medium', 'T2 Medium'), ('m5.large', 'M5 Large'), ('t2.xlarge', 'T2 Xlarge')], default='t2.medium', help_text='Size of AWS EC2', max_length=50),
        ),
    ]
