# Generated by Django 2.0.5 on 2018-05-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0147_auto_20180524_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='banned_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead was marked as qualified for the last time.', null=True),
        ),
    ]
