# Generated by Django 2.0.5 on 2018-06-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0150_auto_20180604_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundler',
            old_name='google_changeback',
            new_name='google_chargeback',
        ),
    ]
