# Generated by Django 2.0.5 on 2018-06-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0151_auto_20180604_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlerLeadStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress_total', models.IntegerField(default=0)),
                ('in_progress_offline', models.IntegerField(default=0)),
                ('in_progress_wrong_pw', models.IntegerField(default=0)),
                ('in_progress_security_checkpoint', models.IntegerField(default=0)),
                ('in_progress_total_issue', models.IntegerField(default=0)),
                ('autobans_last_30_days', models.IntegerField(default=0)),
                ('autobans_total', models.IntegerField(default=0)),
                ('bans_last_30_days', models.IntegerField(default=0)),
                ('bans_total', models.IntegerField(default=0)),
                ('qualified_today', models.IntegerField(default=0)),
                ('qualified_yesterday', models.IntegerField(default=0)),
                ('qualified_last_30_days', models.IntegerField(default=0)),
                ('qualified_total', models.IntegerField(default=0)),
                ('delivered_not_connected', models.IntegerField(default=0)),
                ('delivered_not_connected_last_30_days', models.IntegerField(default=0)),
                ('delivered_last_30_days', models.IntegerField(default=0)),
                ('banned_from_qualified_last_30_days', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bundler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsrental.Bundler')),
            ],
        ),
    ]
