# Generated by Django 2.0.5 on 2018-06-11 20:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0153_ec2instance_is_essential'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='amazon_chargeback',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for AMazon accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='amazon_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to parent bundler.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='amazon_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('125'), help_text='Payout for Amazon accounts', max_digits=8),
        ),
    ]
