# Generated by Django 2.0.5 on 2018-06-11 20:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0154_auto_20180611_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundler',
            name='amazon_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('60'), help_text='Payout for Amazon accounts', max_digits=8),
        ),
    ]
