# Generated by Django 2.0.5 on 2018-06-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0156_auto_20180611_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='essential_key',
            field=models.CharField(db_index=True, default='', help_text='Key to differentiate essential instances', max_length=100),
        ),
    ]
