# Generated by Django 2.0.5 on 2018-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0157_ec2instance_essential_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, help_text='Should be unique', max_length=255, null=True, unique=True),
        ),
    ]
