# Generated by Django 2.0.5 on 2018-06-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0158_auto_20180614_1206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadaccount',
            unique_together={('username', 'account_type', 'lead')},
        ),
    ]
