# Generated by Django 2.0.5 on 2018-06-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0159_auto_20180614_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadaccount',
            unique_together={('account_type', 'lead'), ('username', 'account_type', 'lead')},
        ),
    ]
