# Generated by Django 2.0.5 on 2018-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0160_auto_20180614_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='browser_type',
            field=models.CharField(default='Unknown', help_text='Browser used on EC2', max_length=20),
        ),
    ]
