# Generated by Django 2.0.5 on 2018-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0162_user_allowed_raspberry_pis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_raspberry_pis',
            field=models.ManyToManyField(blank=True, null=True, to='adsrental.RaspberryPi'),
        ),
    ]
