# Generated by Django 2.0.6 on 2018-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0166_auto_20180620_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='primary',
            field=models.BooleanField(default=False, help_text='First added account for this lead'),
        ),
    ]
