# Generated by Django 2.0.6 on 2018-06-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0168_auto_20180622_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadchange',
            name='lead_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsrental.LeadAccount'),
        ),
    ]
