# Generated by Django 2.0.6 on 2018-06-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0169_leadchange_lead_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadaccount',
            name='antidetect_last_touch_date',
        ),
        migrations.RemoveField(
            model_name='leadaccount',
            name='antidetect_touch_count',
        ),
    ]
