# Generated by Django 2.0.7 on 2018-07-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0173_leadhistorymonth_move_to_next_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistorymonth',
            name='check_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
