# Generated by Django 2.0.7 on 2018-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0174_leadhistorymonth_check_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='shipstation_order_status',
            field=models.CharField(blank=True, help_text='Populated by cron script.', max_length=100, null=True),
        ),
    ]
