# Generated by Django 2.0.7 on 2018-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0176_auto_20180716_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
