# Generated by Django 2.0.7 on 2018-07-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0177_auto_20180719_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistorymonth',
            name='note',
            field=models.TextField(blank=True, help_text='Note about payment calc', null=True),
        ),
    ]
