# Generated by Django 2.0.7 on 2018-07-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0179_auto_20180726_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='VultrInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Vultr ID.', null=True)),
                ('label', models.CharField(help_text='Label field from Vultr', max_length=255)),
                ('os', models.CharField(help_text='OS field from Vultr', max_length=255)),
                ('ip_address', models.CharField(help_text='Main IP field from Vultr', max_length=50)),
                ('status', models.CharField(help_text='Status field from Vultr', max_length=20)),
                ('password', models.CharField(help_text='Default password field from Vultr', max_length=255)),
                ('tag', models.CharField(help_text='Tag field from Vultr', max_length=255)),
                ('data', models.TextField(help_text='Full data from Vultr')),
            ],
        ),
    ]
