# Generated by Django 2.0.7 on 2018-07-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0179_auto_20180726_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='in_progress_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead was marked as in-progress.', null=True),
        ),
    ]
