# Generated by Django 2.0.7 on 2018-08-01 18:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0181_leadaccount_in_progress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistorymonth',
            name='amount_moved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount moved from next month', max_digits=6),
        ),
        migrations.AlterField(
            model_name='vultrinstance',
            name='status',
            field=models.CharField(help_text='Power status field from Vultr', max_length=20),
        ),
    ]
