# Generated by Django 2.0.7 on 2018-08-03 19:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0182_auto_20180801_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistory',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Sum to be paid to lead', max_digits=8),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='checks_wrong_password_amazon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='checks_wrong_password_facebook',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='checks_wrong_password_google',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='note',
            field=models.TextField(blank=True, help_text='Note about payment calc', null=True),
        ),
    ]
