# Generated by Django 2.0.7 on 2018-08-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0183_auto_20180803_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadhistory',
            options={'verbose_name': 'Lead Timestamp', 'verbose_name_plural': 'Lead Timestamps'},
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='checks_sec_checkpoint_amazon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='checks_sec_checkpoint_facebook',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='checks_sec_checkpoint_google',
            field=models.IntegerField(default=0),
        ),
    ]
