# Generated by Django 2.0.7 on 2018-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0184_auto_20180803_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistorymonth',
            name='days_sec_checkpoint',
            field=models.IntegerField(default=0, help_text='Days when security checkpoint was reported at least 3 hours.'),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='days_offline',
            field=models.IntegerField(default=0, help_text='Days when device had been online less than 3 hours.'),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='days_online',
            field=models.IntegerField(default=0, help_text='Days when device had been online more than 3 hours.'),
        ),
        migrations.AlterField(
            model_name='leadhistorymonth',
            name='days_wrong_password',
            field=models.IntegerField(default=0, help_text='Days when wrong password was reported at least 3 hours.'),
        ),
    ]
