# Generated by Django 2.0.7 on 2018-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0185_auto_20180810_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
