# Generated by Django 2.1 on 2018-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0186_auto_20180814_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='disqualified_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead was marked as disqualified for the last time.', null=True),
        ),
    ]
