# Generated by Django 2.1 on 2018-08-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0187_leadaccount_disqualified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='is_mla',
            field=models.BooleanField(default=False, help_text='If True - RPi gets latest firmwares'),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='rpid_numeric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='rtunnel_port',
            field=models.PositiveIntegerField(blank=True, help_text='Port to create a reverse tunnel from proxykeeper', null=True),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='tunnel_port',
            field=models.PositiveIntegerField(blank=True, help_text='Port to create a tunnel to proxykeeper', null=True),
        ),
    ]
