# Generated by Django 2.1 on 2018-08-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0188_auto_20180822_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='rtunnel_port',
            field=models.PositiveIntegerField(blank=True, help_text='Port to create a reverse tunnel from proxykeeper', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='tunnel_port',
            field=models.PositiveIntegerField(blank=True, help_text='Port to create a tunnel to proxykeeper', null=True, unique=True),
        ),
    ]
