# Generated by Django 2.1 on 2018-08-22 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0189_auto_20180822_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
