# Generated by Django 2.1 on 2018-08-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0191_raspberrypi_new_config_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberrypi',
            name='is_mla',
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='is_proxy_tunnel',
            field=models.BooleanField(default=False, help_text='If True - RPi works as an HTTP proxy'),
        ),
    ]
