# Generated by Django 2.1 on 2018-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0192_auto_20180822_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='is_beta',
            field=models.BooleanField(default=False, help_text='If True - RPi gets beta firmwares'),
        ),
    ]
