# Generated by Django 2.1 on 2018-08-28 23:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0193_raspberrypi_is_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='amazon_second_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to second parent bundler.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='facebook_second_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to second parent bundler.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='google_second_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to second parent bundler.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='second_parent_bundler',
            field=models.ForeignKey(blank=True, help_text='Second Bundler that gets part of the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_child_bundler', to='adsrental.Bundler'),
        ),
    ]
