# Generated by Django 2.1 on 2018-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0196_auto_20180909_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='proxy_hostname',
            field=models.CharField(choices=[('Adsrental', 'adsrental.com'), ('Proxykeeper', '178.128.1.68'), ('Proxykeeper2', '138.197.219.240')], default='178.128.1.68', help_text='Hostname tunnel to proxykeeper', max_length=50),
        ),
    ]
