# Generated by Django 2.1 on 2018-09-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0197_auto_20180909_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='proxy_hostname',
            field=models.CharField(choices=[('adsrental.com', 'Adsrental'), ('178.128.1.68', 'Proxykeeper'), ('138.197.219.240', 'Proxykeeper2')], default='178.128.1.68', help_text='Hostname tunnel to proxykeeper', max_length=50),
        ),
    ]
