# Generated by Django 2.1 on 2018-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0199_remove_lead_tested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='proxy_hostname',
            field=models.CharField(choices=[('178.128.1.68', 'Proxykeeper'), ('138.197.219.240', 'Proxykeeper2')], default='178.128.1.68', help_text='Hostname tunnel to proxykeeper', max_length=50),
        ),
    ]
