# Generated by Django 2.1 on 2018-09-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0200_auto_20180911_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypisession',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
