# Generated by Django 2.1 on 2018-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0201_raspberrypisession_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProxyLeadAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Report LeadAccount',
                'verbose_name_plural': 'Report LeadAccounts',
                'proxy': True,
                'indexes': [],
            },
            bases=('adsrental.leadaccount',),
        ),
        migrations.AlterField(
            model_name='leadaccount',
            name='account_type',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Facebook Screenshot', 'Facebook Screenshot'), ('Google', 'Google'), ('Amazon', 'Amazon')], max_length=50),
        ),
    ]
