# Generated by Django 2.1 on 2018-10-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0202_auto_20181017_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccount',
            name='old_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified'), ('Screenshot Disqualified', 'Screenshot Disqualified')], default=None, help_text='Used to restore previous status on Unban action', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadaccount',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified'), ('Screenshot Disqualified', 'Screenshot Disqualified')], default='Available', max_length=50),
        ),
    ]
