# Generated by Django 2.1 on 2018-10-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0203_auto_20181017_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='isp',
            field=models.CharField(blank=True, help_text='Internet Service Provider', max_length=255, null=True),
        ),
    ]
