# Generated by Django 2.1 on 2018-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0205_auto_20181017_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='apartment',
            field=models.CharField(blank=True, help_text='Apartment/suite', max_length=255, null=True),
        ),
    ]
