# Generated by Django 2.1 on 2018-10-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0207_auto_20181018_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccount',
            name='old_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified'), ('Screenshot Qualified', 'Screenshot Qualified'), ('Screenshot Disqualified', 'Screenshot Disqualified'), ('Needs approval', 'Needs approval')], default=None, help_text='Used to restore previous status on Unban action', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadaccount',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified'), ('Screenshot Qualified', 'Screenshot Qualified'), ('Screenshot Disqualified', 'Screenshot Disqualified'), ('Needs approval', 'Needs approval')], default='Available', max_length=50),
        ),
    ]
