# Generated by Django 2.1 on 2018-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0208_auto_20181022_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='old_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified'), ('Needs approval', 'Needs approval')], default=None, help_text='Used to restore previous status on Unban action', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Banned', 'Banned'), ('Qualified', 'Qualified'), ('In-Progress', 'In-Progress'), ('Disqualified', 'Disqualified'), ('Needs approval', 'Needs approval')], default='Available', help_text='All statuses except for Banned are considered as Active', max_length=40),
        ),
    ]
