# Generated by Django 2.1.3 on 2018-11-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0209_auto_20181025_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadaccount',
            old_name='url',
            new_name='account_url',
        ),
    ]
