# Generated by Django 2.1.3 on 2018-12-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0211_auto_20181203_0850'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('street', 'apartment', 'city', 'country', 'state')},
        ),
    ]
