# Generated by Django 2.1.4 on 2019-01-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0213_auto_20181221_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccount',
            name='qualified_date',
            field=models.DateTimeField(blank=True, help_text='Date when lead was marked as qualified for the first time.', null=True),
        ),
    ]
