# Generated by Django 2.1.5 on 2019-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0215_auto_20190118_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='wrong_password_change_counter',
            field=models.IntegerField(default=0, help_text='How many times a password was changed by user.'),
        ),
    ]
