# Generated by Django 2.1.5 on 2019-01-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0218_auto_20190122_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='ban_note',
            field=models.TextField(blank=True, help_text='Populated from ban form', null=True),
        ),
    ]
