# Generated by Django 2.1.5 on 2019-01-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0219_leadaccount_ban_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadchange',
            name='field',
            field=models.CharField(choices=[('address', 'Address'), ('email', 'Email'), ('first_name', 'First name'), ('last_name', 'Last name'), ('password', 'Password'), ('pi_delivered', 'RPi delivered'), ('prepare_for_reshipment', 'Prepare for reshipment'), ('security_checkpoint', 'Security checkpoint'), ('status', 'Status'), ('wrong_password', 'Wrong password'), ('wrong_password_fix', 'Wrong password fixed')], max_length=255),
        ),
    ]
