# Generated by Django 2.1.5 on 2019-02-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0220_auto_20190125_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccount',
            name='adsdb_account_id',
            field=models.CharField(blank=True, help_text='Corresponding Account ID in Adsdb database. used for syncing between databases.', max_length=255, null=True, unique=True),
        ),
    ]
