# Generated by Django 2.1.5 on 2019-02-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0221_auto_20190201_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='last_not_qualified_reported',
            field=models.DateTimeField(blank=True, help_text='Date whennot qualified notification was sent.', null=True),
        ),
    ]
