# Generated by Django 2.1.5 on 2019-02-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0222_leadaccount_last_not_qualified_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bundler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adsrental.Bundler')),
                ('lead_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adsrental.LeadAccount')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsrental.BundlerPaymentsReport')),
            ],
        ),
    ]
