# Generated by Django 2.1.5 on 2019-02-17 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0224_bundlerpayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlerpayment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bundlerpayment',
            name='payment_type',
            field=models.CharField(choices=[('account', 'Lead account activated'), ('account_parent', "Child's Lead account activated"), ('account_second_parent', "Child's Lead account activated (2nd parent)"), ('bonus', 'Bonus')], default='account', max_length=50),
        ),
    ]
