# Generated by Django 2.1.5 on 2019-02-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0226_auto_20190217_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlerpayment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bundlerpayment',
            name='payment_type',
            field=models.CharField(choices=[('account', 'Lead account activated'), ('account_parent', "Child's Lead account activated"), ('account_second_parent', "Child's Lead account activated (2nd parent)"), ('bonus', 'Bonus'), ('chargeback', 'Chargeback')], default='account', max_length=50),
        ),
    ]
