# Generated by Django 2.1.5 on 2019-02-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0227_auto_20190217_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlerpayment',
            name='ready',
            field=models.BooleanField(default=True),
        ),
    ]
