# Generated by Django 2.1.5 on 2019-02-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0229_auto_20190217_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlerpayment',
            name='paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
