# Generated by Django 2.1.7 on 2019-03-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0231_bundlerpayment_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='slack_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
