# Generated by Django 2.1.7 on 2019-03-12 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0231_bundlerpayment_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAccountIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('Ban Account Request', 'Ban Account Request'), ('Connection Issue', 'Connection Issue'), ('Wrong Password', 'Wrong Password'), ('Security Checkpoint', 'Security Checkpoint'), ('Phone Number Change', 'Phone Number Change'), (
                    'Address Change', 'Address Change'), ('Reshipment Needed', 'Reshipment Needed'), ('Missing Payment', 'Missing Payment'), ('Returned Check', 'Returned Check'), ('Charge to Account', 'Charge to Account'), ('Bill Left on Account', 'Bill Left on Account')], max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('note', models.TextField(default='')),
                ('new_value', models.TextField(default='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lead_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_accounts', related_query_name='lead_account_issue', to='adsrental.LeadAccount')),
            ],
        ),
    ]
