# Generated by Django 2.1.7 on 2019-04-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0234_auto_20190314_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bundler',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Bundler team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundlers', to='adsrental.BundlerTeam'),
        ),
    ]
