# Generated by Django 2.1.7 on 2019-04-02 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0235_auto_20190402_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccountissue',
            name='lead_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', related_query_name='issue', to='adsrental.LeadAccount'),
        ),
    ]
