# Generated by Django 2.1.7 on 2019-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0236_auto_20190402_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaccountissue',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Submitted', 'Fix submitted'), ('Rejected', 'Rejected'), ('Reshipped', 'Reshipped'), ('Cancelled', 'Cancelled'), ('Verified', 'Verified'), ('Paid', 'Paid')], default='Reported', max_length=50),
        ),
    ]
