# Generated by Django 2.1.7 on 2019-04-22 13:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0242_auto_20190419_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='amazon_third_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to third parent bundler.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='facebook_screenshot_third_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to parent bundler.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='facebook_third_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to third parent bundler.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='google_third_parent_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount to withdraw from lead payment to be paid to third parent bundler.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='third_parent_bundler',
            field=models.ForeignKey(blank=True, help_text='Third Bundler that gets part of the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_child_bundler', to='adsrental.Bundler'),
        ),
        migrations.AlterField(
            model_name='bundlerpayment',
            name='payment_type',
            field=models.CharField(choices=[('account', 'Lead account activated'), ('account_parent', "Child's Lead account activated"), ('account_second_parent', "Child's Lead account activated (2nd parent)"), ('account_third_parent', "Child's Lead account activated (3rd parent)"), ('bonus', 'Bonus'), ('chargeback', 'Chargeback')], db_index=True, default='account', max_length=50),
        ),
    ]
