# Generated by Django 2.1.7 on 2019-04-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0243_auto_20190422_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='proxy_hostname',
            field=models.CharField(choices=[('178.128.1.68', 'Proxykeeper'), ('138.197.219.240', 'Proxykeeper2'), ('138.197.197.65', 'Proxykeeper3'), ('157.230.146.152', 'Proxykeeper4'), ('157.230.155.97', 'Proxykeeper5')], default='178.128.1.68', help_text='Hostname tunnel to proxykeeper', max_length=50),
        ),
    ]
