# Generated by Django 2.1.7 on 2019-04-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0244_auto_20190422_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaccount',
            name='disable_auto_ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
