# Generated by Django 2.1.7 on 2019-04-25 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0244_auto_20190422_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Not shown when you hover user name in admin interface.', null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='comments',
            field=models.ManyToManyField(to='adsrental.Comment'),
        ),
        migrations.AddField(
            model_name='leadaccount',
            name='comments',
            field=models.ManyToManyField(to='adsrental.Comment'),
        ),
        migrations.AddField(
            model_name='leadaccountissue',
            name='comments',
            field=models.ManyToManyField(to='adsrental.Comment'),
        ),
    ]
