# Generated by Django 2.1.7 on 2019-04-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0245_comment_commentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
