# Generated by Django 2.1.7 on 2019-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0245_auto_20190425_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='comments',
            field=models.ManyToManyField(blank=True, to='adsrental.Comment'),
        ),
        migrations.AlterField(
            model_name='leadaccount',
            name='comments',
            field=models.ManyToManyField(blank=True, to='adsrental.Comment'),
        ),
        migrations.AlterField(
            model_name='leadaccountissue',
            name='comments',
            field=models.ManyToManyField(blank=True, to='adsrental.Comment'),
        ),
    ]
