# Generated by Django 2.1.7 on 2019-05-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0246_bundler_url_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
