# Generated by Django 2.1.7 on 2019-05-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0247_lead_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
