# Generated by Django 2.1.7 on 2019-07-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0246_auto_20190426_1708'),
        ('adsrental', '0248_auto_20190522_1425'),
    ]

    operations = [
    ]
