# Generated by Django 2.1.7 on 2019-07-12 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0249_merge_20190705_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundler',
            name='amazon_chargeback_30_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Amazon 30+ days active accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='amazon_chargeback_60_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Amazon 60+ days active accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='amazon_chargeback_90_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Amazon 90+ days active accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='chargeback_streak',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='How many chargebacks bundler can have in rolling 30 days period.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='facebook_chargeback_30_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Facebook 30+ days active accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='facebook_chargeback_60_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Facebook 60+ days active accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='facebook_chargeback_90_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Facebook 90+ days active accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='google_chargeback_30_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Google 30+ days active accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='google_chargeback_60_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Google 60+ days active accounts.', max_digits=8),
        ),
        migrations.AddField(
            model_name='bundler',
            name='google_chargeback_90_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Chargeback value for Google 90+ days active accounts.', max_digits=8),
        ),
    ]
