# Generated by Django 2.1.7 on 2019-07-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0251_auto_20190712_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundler',
            name='chargeback_streak',
            field=models.IntegerField(default=3, help_text='How many chargebacks bundler can have in rolling 30 days period.'),
        ),
    ]
