# Generated by Django 2.1.7 on 2019-08-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0252_auto_20190721_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='proxy_delay',
            field=models.FloatField(blank=True, default=None, help_text='Proxy response from tunnel', null=True),
        ),
    ]
