# Generated by Django 2.1.7 on 2019-08-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsrental', '0253_raspberrypi_proxy_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='proxy_delay_datetime',
            field=models.DateTimeField(blank=True, help_text='Date of tunnel last check', null=True),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='proxy_hostname',
            field=models.CharField(choices=[('178.128.1.68', 'Proxykeeper'), ('138.197.219.240', 'Proxykeeper2'), ('138.197.197.65', 'Proxykeeper3'), ('157.230.146.152', 'Proxykeeper4'), ('157.230.155.97', 'Proxykeeper5'), ('134.209.52.3', 'Proxykeeper6'), ('68.183.163.172', 'Proxykeeper7')], default='178.128.1.68', help_text='Hostname tunnel to proxykeeper', max_length=50),
        ),
    ]
