Feature('Admin check lead accounts')

Scenario('Check lead accounts', (I)=>{
    I.amOnPage('http://localhost:8443/app/admin/')
    I.see('Adsrental Administration')
    I.fillField('input[name="username"]', 'volshebnyi@gmail.com')
    I.fillField('input[name="password"]', 'team17')
    I.click('Log in')
    I.see('Dashboard')
    I.click('Lead accounts')
    I.see('Select lead account to change')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Approve account')
    I.click('Go')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Marck as Qualified,Assign RPI,create Shipstation order')
    I.click('Go')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Mark as disqualified')
    I.click('Go')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Mark as avalible from disqualified')
    I.click('Go')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban')
    I.click('Go')
    I.click('Home')
    I.see('Dashboard')
    I.click('Lead accounts')
    I.see('Select lead account to change')
    I.fillField('input[name="q"', 'Epiphany Alston')
    I.checkOption('input[name="_selected_action"]')
    I.I.fillField('select[name="action"]', 'Unban')
    I.click('Go')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Report wrong password')
    I.click('Go')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Report security checkpoint')
    I.click('Go')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'DEBUG: Sync to ADSDB')
    I.click('Go')

});