Feature('Admin bununban Test')

Scenario('Ban unban lead', (I)=>{
    I.amOnPage('http://localhost:8443/app/admin/')
    I.see('Adsrental Administration')
    I.fillField('input[name="username"]', 'volshebnyi@gmail.com')
    I.fillField('input[name="password"]', 'team17')
    I.click('Log in')
    I.see('Dashboard')
    I.click('Leads') 
    I.fillField('input[name="q"', 'Vlad Emelianov ')
    I.click('Search')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban google account')
    I.click('Go')
    I.see('Choose reason to ban Google account')
    I.fillField('textarea[name="note"]', 'need bun')
    I.click('Ban')
    I.see('banned')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Unban google account')
    I.click('Go')
    I.see('In-Progress')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban facebook account')
    I.click('Go')
    I.see('Choose reason to ban Facebook account')
    I.fillField('textarea[name="note"]', 'need bun')
    I.click('Ban')
    I.see('banned')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Unban facebook account')
    I.click('Go')
    I.see('In-Progress')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban amazon account')
    I.click('Go')
    I.see('Choose reason to ban Amazon account')
    I.fillField('textarea[name="note"]', 'need bun')
    I.click('Ban')
    I.see('banned')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Unban facebook account')
    I.click('Go')
    I.see('In-Progress')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban lead')
    I.click('Go')
    I.see('has active accounts, ban them first.')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban google account')
    I.click('Go')
    I.see('Choose reason to ban Google account')
    I.fillField('textarea[name="note"]', 'need bun')
    I.click('Ban')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban google account')
    I.click('Go')
    I.see('Choose reason to ban Google account')
    I.fillField('textarea[name="note"]', 'need bun')
    I.click('Ban')
    I.see('banned')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban facebook account')
    I.click('Go')
    I.see('Choose reason to ban Facebook account')
    I.fillField('textarea[name="note"]', 'need bun')
    I.click('Ban')
    I.see('banned')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban amazon account')
    I.click('Go')
    I.see('Choose reason to ban Amazon account')
    I.fillField('textarea[name="note"]', 'need bun')
    I.click('Ban')
    I.see('banned')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Ban lead')
    I.click('Go')
    I.see('is banned')
    I.checkOption('input[name="_selected_action"]')
    I.fillField('select[name="action"]', 'Unban lead')
    I.click('Go')
    I.see('is unbanned')
    I.see('In-Progress')





});